export const data = [
  {
    id: 1,
    header: "Table of Contents",
    type: "Table of Contents",
    status: "Done",
    target: "10",
    limit: "15",
    reviewer: "Eddie Lake",
  },
  {
    id: 2,
    header: "Executive Summary",
    type: "Executive Summary",
    status: "In Progress",
    target: "5",
    limit: "10",
    reviewer: "Jamik Tashpulatov",
  },
  {
    id: 3,
    header: "Technical Approach",
    type: "Technical Approach",
    status: "Not Started",
    target: "20",
    limit: "25",
    reviewer: "Assign reviewer",
  },
  {
    id: 4,
    header: "Design",
    type: "Design",
    status: "Done",
    target: "8",
    limit: "12",
    reviewer: "Emily Whalen",
  },
  {
    id: 5,
    header: "Capabilities",
    type: "Capabilities",
    status: "In Progress",
    target: "15",
    limit: "20",
    reviewer: "Eddie Lake",
  },
]